# np and pandas

In [7]:
import numpy as np

In [8]:
simple_list=[6,8,9]
np.array(simple_list)

array([6, 8, 9])

In [9]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [12]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
np.arange(1,31,5)

array([ 1,  6, 11, 16, 21, 26])

In [14]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(15,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.zeros((2,9),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

# linespace

In [20]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [21]:
np.linspace(0,20,7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [22]:
np.eye((11))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(3,5)

array([[0.84526166, 0.50919983, 0.32901498, 0.84248625, 0.12500562],
       [0.00634696, 0.91726915, 0.38571724, 0.39041527, 0.06805438],
       [0.73648872, 0.14496246, 0.94829727, 0.37116669, 0.31077185]])

In [25]:
arr=np.random.randn(2,4)
arr

array([[-0.7910256 ,  0.79351787, -1.47652968,  1.1264807 ],
       [ 0.43712675,  0.63821168,  0.98633976, -0.88091046]])

In [28]:
np.random.randint(2,100)

81

In [29]:
np.random.randint(20,55,145)

array([28, 39, 36, 38, 35, 26, 27, 42, 48, 42, 35, 35, 35, 43, 37, 47, 27,
       30, 30, 38, 47, 32, 35, 22, 22, 37, 22, 54, 26, 40, 30, 50, 30, 43,
       44, 22, 45, 44, 54, 30, 42, 41, 34, 20, 40, 43, 44, 38, 46, 42, 35,
       22, 54, 54, 27, 23, 38, 53, 32, 23, 31, 42, 42, 31, 36, 21, 40, 51,
       22, 53, 35, 47, 32, 40, 51, 47, 20, 52, 47, 21, 22, 35, 49, 43, 34,
       53, 53, 29, 42, 35, 27, 37, 31, 36, 39, 34, 48, 33, 39, 32, 28, 30,
       45, 34, 34, 34, 34, 37, 24, 25, 45, 42, 37, 26, 52, 45, 38, 39, 20,
       21, 47, 45, 25, 35, 51, 24, 22, 23, 41, 45, 30, 39, 51, 43, 36, 36,
       50, 27, 26, 38, 24, 34, 21, 46, 30])

In [30]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
rand_array=np.random.randint(0,100,22)
rand_array

array([92, 27,  5,  5, 14, 27,  2, 56, 45, 99, 45, 21, 79, 29,  3, 11, 52,
        6, 11, 24, 95, 21])

In [33]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [36]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [37]:
rand_array.max()

99

In [39]:
rand_array.argmax()

9

In [40]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
a=np.random.rand(2,3)
a

array([[0.19551349, 0.25112861, 0.8383643 ],
       [0.31102771, 0.41802426, 0.48070393]])

In [44]:
a.T

array([[0.19551349, 0.31102771],
       [0.25112861, 0.41802426],
       [0.8383643 , 0.48070393]])

In [47]:
sample_array=np.arange(10,22)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [48]:
sample_array[0]

10

In [49]:
sample_array[2:5]

array([12, 13, 14])

In [51]:
sample_array[1:4]=150
sample_array

array([ 10, 150, 150, 150,  14,  15,  16,  17,  18,  19,  20,  21])

In [54]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [56]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [58]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two-Dimensional array

In [59]:
import numpy as np

In [60]:
sample_matrix=np.array([[50,21,4,29],[56,89,54,78],[98,56,45,15]])
sample_matrix

array([[50, 21,  4, 29],
       [56, 89, 54, 78],
       [98, 56, 45, 15]])

In [61]:
sample_matrix[1,3]

78

In [62]:
sample_matrix[2,:]

array([98, 56, 45, 15])

In [63]:
sample_matrix[0]

array([50, 21,  4, 29])

In [64]:
sample_matrix[:,(2,3)]

array([[ 4, 29],
       [54, 78],
       [45, 15]])

### Selection Technique